apiVersion: v1
kind: Service
metadata:
  name: security-playground
  namespace: security-playground
  labels:
    app.kubernetes.io/instance: security-playground
    app.kubernetes.io/name: security-playground
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30000
  selector:
    app.kubernetes.io/instance: security-playground
    app.kubernetes.io/name: security-playground