apiVersion: v1
kind: Service
metadata:
  name: security-playground-restricted-nomalware
  namespace: security-playground-restricted-nomalware
  labels:
    app.kubernetes.io/instance: security-playground-restricted-nomalware
    app.kubernetes.io/name: security-playground-restricted-nomalware
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30003
  selector:
    app.kubernetes.io/instance: security-playground-restricted-nomalware
    app.kubernetes.io/name: security-playground-restricted-nomalware